### ISSUE TITLE
fix code climate issues

### ISSUE THREAD

**Issue by bzlibby** [ssube/cautious-journey#84]
https://codeclimate.com/github/ssube/cautious-journey/issues#

- [x] resolveLabels function is too complex & too long - found in resolve.ts
- [x] graphLabels function is too complex & too long - found in graph.ts
- [x] main function is too long - found in main.ts
- [x] syncProjectLabels function is too complex & too long - found in sync.ts
- [x] syncIssuesLabels function is too long - found in sync.ts
- [x] checkLabelRules function is too long - found in resolve.ts
- [x] dotGraph function is too long - found in graph.ts
- [x] multiple blocks of code that are similar or identical - found in graph.ts and github.ts

**Comment by ssube** [comment]
Down to 4, all fairly simple:

- `main` takes 5 params (max 4)
- `resolveBaseLabel` is too complex
- `resolveState` is too complex
- `syncProjectLabels` is too complex
